branch-defaults:
  cf-deploy:
    environment: cf-production
  cf-staging:
    environment: cf-staging
global:
  # Use deploy.sh to change this to the correct application name
  application_name: cryptosophy_forum
  branch: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
