name: Run Cypress Tests
on:
  push:
  pull_request:
    branches-ignore:
      - ea-deploy
  workflow_dispatch:
concurrency: cypress
jobs:
  buildAndRunCypressTests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Environment
      id: setup-environment
      uses: ./.github/actions/setupEnvironment

    - name: Cypress run
      uses: cypress-io/github-action@v4
      env:
        TESTING_DB_URL: ${{ secrets.TESTING_DB_URL }}
        PG_URL: ${{ secrets.PG_URL }}
        CYPRESS_CACHE_FOLDER: ${{ steps.setup-environment.outputs.cypress-cache-folder }}
      with:
          start: yarn ea-start-testing-db
          command: yarn ci-cypress-run

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Upload screenshots
        path: cypress/screenshots

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Upload videos
        path: cypress/videos
