
name: Deploy prod
on:
  push:
    branches: [cf-prod]
jobs:
  build:
    name: Build Image and push
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate image tag
        id: git
        run: echo "::set-output name=SHA::$(git rev-parse --short=8 HEAD)"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cryptosophyforum
          IMAGE_TAG: ${{ steps.git.outputs.SHA }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Deploy new image to eb ----
      - name: Configure environment variables for prod
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL_PROD }}" >> $GITHUB_ENV
          echo "SETTINGS_FILE_NAME=settings-prod.json" >> $GITHUB_ENV
          echo "Added prod environment variable(s)"

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ">=3.5"

      - run: pip3 install --upgrade pip awsebcli

      - name: Substitute placeholder environment variables with repository-configured values
        run: |
          sed -i.bak "s|secrets\.MONGO_URL|${{ env.MONGO_URL }}|" docker-compose.yml
          sed -i.bak "s|secrets\.SETTINGS_FILE_NAME|${{ env.SETTINGS_FILE_NAME }}|" docker-compose.yml
          sed -i.bak "s|secrets\.IMAGE_TAG|${{ steps.git.outputs.SHA }}|" docker-compose.yml
          sed -i.bak "s|secrets\.SMTP_USER|${{ secrets.SMTP_USER }}|" docker-compose.yml
          sed -i.bak "s|secrets\.SMTP_PASSWORD|${{ secrets.SMTP_PASSWORD }}|" docker-compose.yml

      - name: Include the modified docker-compose.yml in the to-be-deployed changes
        run: |
          git config --global user.name github_action
          git config --global user.email github_action@github.com
          git add docker-compose.yml
      - name: Execute deployment
        run: eb deploy --verbose --staged --timeout 20
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
