name: Run Unit Tests
on:
  push:
  pull_request:
    branches-ignore:
      - ea-deploy
  workflow_dispatch:
jobs:
  runLint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment
    - run: yarn run eslint

  runTypecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment
    - run: yarn run tsc

  runUnitTests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment
    - run: yarn run unit-ci || git diff --no-index schema/accepted_schema.sql schema/schema_to_accept.sql

  runIntegrationTests:
    concurrency: integration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment
    - name: Seed integration database
      if: failure()
      env:
        TESTING_DB_URL: ${{ secrets.TESTING_DB_URL }}
        PG_URL: ${{ secrets.PG_URL }}
      run: yarn seed-integration-db
    - name: yarn run integration-ci
      env:
        PG_URL: ${{ secrets.PG_URL }}
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: yarn run integration-ci
